# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> Init [[
# ------------------------------------------------------------------------------

version: '2'

services:

# ]]
# ------------------------------------------------------------------------------
# -> Web [[
# ------------------------------------------------------------------------------

  web:
    volumes:
      - ./project:/var/www/project

# ]]
# ------------------------------------------------------------------------------
# -> Nginx [[
# ------------------------------------------------------------------------------

  nginx:
    build: ./image/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443

# ]]
# ------------------------------------------------------------------------------
# -> Mysql [[
# ------------------------------------------------------------------------------

  mysql:
    build: ./image/mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: devbox

# ]]
# ------------------------------------------------------------------------------
# -> Postgres [[
# ------------------------------------------------------------------------------

  postgres:
    image: postgres:9.6.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devbox

# ]]
# ------------------------------------------------------------------------------
# -> Mongo [[
# ------------------------------------------------------------------------------

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

# ]]
# ------------------------------------------------------------------------------
# -> Redis [[
# ------------------------------------------------------------------------------

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

# ]]
# ------------------------------------------------------------------------------
# -> Memcached [[
# ------------------------------------------------------------------------------

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - 11211:11211

# ]]
# ------------------------------------------------------------------------------
# -> Mailhog [[
# ------------------------------------------------------------------------------

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025

# ]]
# ------------------------------------------------------------------------------
