# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> Init [[
# ------------------------------------------------------------------------------

version: '2'

services:

# ]]
# ------------------------------------------------------------------------------
# -> PHP-FPM [[
# ------------------------------------------------------------------------------

  php-fpm:
    build:
      context: ./image/php
      args:
        - INSTALL_XDEBUG=false
        - INSTALL_COMPOSER=false
        - INSTALL_PHPUNIT=false
        - INSTALL_MAGERUN=false
        - INSTALL_MAGERUN_2=false
        - INSTALL_SQLITE=false
        - PHP_INSTALL_MCRYPT=false
        - PHP_INSTALL_XSL=false
        - PHP_INSTALL_INTL=false
        - PHP_INSTALL_GD=false
        - PHP_INSTALL_SOAP=false
        - PHP_INSTALL_ZIP_ARCHIVE=false
        - PHP_INSTALL_MEMCACHED=false
        - PHP_INSTALL_MONGO=false
      dockerfile: Dockerfile
    container_name: php
    extends:
        file: common.yml
        service: web

# ]]
# ------------------------------------------------------------------------------
# -> Nginx [[
# ------------------------------------------------------------------------------

  nginx:
    extends:
        file: common.yml
        service: nginx
    volumes_from:
      - php-fpm
    links:
      - php-fpm

# ]]
# ------------------------------------------------------------------------------
