# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> 1. Web [[
# ------------------------------------------------------------------------------

web:
  build: ./image/nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - php:php
  volumes:
    - ./project:/project
    - ./image/nginx/sites:/etc/nginx/conf.d

# ]]
# ------------------------------------------------------------------------------
# -> 2.PHP [[
# ------------------------------------------------------------------------------

php:
  build: ./image/php/5.6
  links:
    - mysql:mysql
    - mailhog:mailhog
    - redis:redis
  volumes:
    - ./project:/project
    - ./log/php-fpm:/var/log/php-fpm¬

# ]]
# ------------------------------------------------------------------------------
# -> 3. Mysql [[
# ------------------------------------------------------------------------------

mysql:
  build: ./image/mysql
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: 123

# ]]
# ------------------------------------------------------------------------------
# -> 4. Redis [[
# ------------------------------------------------------------------------------

redis:
  image: redis
  ports:
    - "6379:6379"

# ]]
# ------------------------------------------------------------------------------
# -> 5. Mailhog [[
# ------------------------------------------------------------------------------

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"

# ]]
# ------------------------------------------------------------------------------
