# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> 1. Web [[
# ------------------------------------------------------------------------------

web:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    - memcached:memcached
    - redis:redis
    - mailhog:mailhog
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

# ]]
# ------------------------------------------------------------------------------
# -> 2. Mysql [[
# ------------------------------------------------------------------------------

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123

# ]]
# ------------------------------------------------------------------------------
# -> 3. Memcached [[
# ------------------------------------------------------------------------------

memcached:
  image: memcached
  ports:
    - "11211:11211"

# ]]
# ------------------------------------------------------------------------------
# -> 4. Redis [[
# ------------------------------------------------------------------------------

redis:
  image: redis
  ports:
    - "6379:6379"

# ]]
# ------------------------------------------------------------------------------
# -> 5. Mailhog [[
# ------------------------------------------------------------------------------

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"

# ]]
# ------------------------------------------------------------------------------
