# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> 1.PHP [[
# ------------------------------------------------------------------------------

php:
  build: ./image/php/5.6
  container_name: php
  links:
    - mysql
    - mailhog
    - redis
  volumes:
    - ./project:/var/www/project

# ]]
# ------------------------------------------------------------------------------
# -> 2. Nginx [[
# ------------------------------------------------------------------------------

nginx:
  build: ./image/nginx
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./image/nginx/sites:/etc/nginx/conf.d
  links:
    - php
  ports:
    - 80:80
    - 443:443
    - 9000:9000

# ]]
# ------------------------------------------------------------------------------
# -> 3. Mysql [[
# ------------------------------------------------------------------------------

mysql:
  build: ./image/mysql
  container_name: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: 123

# ]]
# ------------------------------------------------------------------------------
# -> 4. Redis [[
# ------------------------------------------------------------------------------

redis:
  image: redis
  container_name: redis
  ports:
    - 6379:6379

# ]]
# ------------------------------------------------------------------------------
# -> 5. Mailhog [[
# ------------------------------------------------------------------------------

mailhog:
  image: mailhog/mailhog
  container_name: mailhog
  ports:
    - 8025:8025

# ]]
# ------------------------------------------------------------------------------
