# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> Init [[
# ------------------------------------------------------------------------------

version: '2'

services:

# ]]
# ------------------------------------------------------------------------------
# -> PHP-FPM [[
# ------------------------------------------------------------------------------

  php-fpm:
    build:
      context: ./image/php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_COMPOSER=true
        - INSTALL_PHPUNIT=true
        - INSTALL_SQLITE=true
        - PHP_INSTALL_MCRYPT=true
        - PHP_INSTALL_XSL=true
        - PHP_INSTALL_INTL=true
        - PHP_INSTALL_GD=true
        - PHP_INSTALL_SOAP=true
        - PHP_INSTALL_ZIP_ARCHIVE=true
    extends:
        file: services.yml
        service: php-fpm

# ]]
# ------------------------------------------------------------------------------
# -> Python [[
# ------------------------------------------------------------------------------

  # python:
  #   extends:
  #       file: services.yml
  #       service: python

# ]]
# ------------------------------------------------------------------------------
# -> Nginx [[
# ------------------------------------------------------------------------------

  nginx:
    extends:
        file: services.yml
        service: nginx
    volumes_from:
      - php-fpm
      # - python
    links:
      - php-fpm
      # - python

# ]]
# ------------------------------------------------------------------------------
