# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> 1. PHP [[
# ------------------------------------------------------------------------------

php:
  build: ./image/php/5.6
  container_name: php-5.6
  links:
    - mysql
    # - mongo
    # - mailhog
    # - redis
    # - memcached
  volumes:
    - ./project:/var/www/project

# ]]
# ------------------------------------------------------------------------------
# -> 2. Nginx [[
# ------------------------------------------------------------------------------

nginx:
  build: ./image/nginx
  container_name: nginx
  volumes_from:
    - php
  links:
    - php
  ports:
    - 80:80
    - 443:443

# ]]
# ------------------------------------------------------------------------------
# -> 3. Mysql [[
# ------------------------------------------------------------------------------

mysql:
  build: ./image/mysql
  container_name: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: 123

# ]]
# ------------------------------------------------------------------------------
# -> 4. Mongo [[
# ------------------------------------------------------------------------------

# mongo:
#   image: mongo
#   container_name: mongo
#   ports:
#     - 27017:27017

# ]]
# ------------------------------------------------------------------------------
# -> 5. Redis [[
# ------------------------------------------------------------------------------

# redis:
#   image: redis:alpine
#   container_name: redis
#   ports:
#     - 6379:6379

# ]]
# ------------------------------------------------------------------------------
# -> 6. Memcached [[
# ------------------------------------------------------------------------------

# memcached:
#   image: memcached:alpine
#   container_name: memcached
#   ports:
#     - 11211:11211

# ]]
# ------------------------------------------------------------------------------
# -> 7. Mailhog [[
# ------------------------------------------------------------------------------

# mailhog:
#   image: mailhog/mailhog
#   container_name: mailhog
#   ports:
#     - 8025:8025

# ]]
# ------------------------------------------------------------------------------
