# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> Init [[
# ------------------------------------------------------------------------------

version: '3'

services:

# ]]
# ------------------------------------------------------------------------------
# -> Nginx [[
# ------------------------------------------------------------------------------

    nginx:
        container_name: nginx
        build: ./image/nginx
        volumes:
            - ./project:/var/www/project
        ports:
            - 80:80
            - 443:443 

# ]]
# ------------------------------------------------------------------------------
# -> PHP-FPM [[
# ------------------------------------------------------------------------------

    php:
        container_name: php
        build: ./image/php
        volumes:
            - ./project:/var/www/project

# ]]
# ------------------------------------------------------------------------------
# -> Mariadb [[
# ------------------------------------------------------------------------------

    mariadb:
        container_name: mariadb
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: devbox
        ports:
            - 3306:3306

# ]]
# ------------------------------------------------------------------------------
# -> Maildev [[
# ------------------------------------------------------------------------------

    maildev:
        container_name: maildev
        image: djfarrelly/maildev
        ports:
            - 8025:80

# ]]
# ------------------------------------------------------------------------------
