# vim: set foldmarker=[[,]] foldlevel=0 foldmethod=marker spell:
# ------------------------------------------------------------------------------
# -> Init [[
# ------------------------------------------------------------------------------

version: '2'

services:

# ]]
# ------------------------------------------------------------------------------
# -> Web [[
# ------------------------------------------------------------------------------

  web:
    volumes:
      - ./project:/var/www/project

# ]]
# ------------------------------------------------------------------------------
# -> PHP-FPM [[
# ------------------------------------------------------------------------------

  php-fpm:
    build:
      context: ./image/php
      args:
        - INSTALL_XDEBUG=false
        - INSTALL_COMPOSER=false
        - INSTALL_PHPUNIT=false
        - INSTALL_MAGERUN=false
        - INSTALL_MAGERUN_2=false
        - INSTALL_SQLITE=false
        - PHP_INSTALL_MCRYPT=false
        - PHP_INSTALL_XSL=false
        - PHP_INSTALL_INTL=false
        - PHP_INSTALL_GD=false
        - PHP_INSTALL_SOAP=false
        - PHP_INSTALL_ZIP_ARCHIVE=false
        - PHP_INSTALL_MEMCACHED=false
        - PHP_INSTALL_MONGO=false
      dockerfile: Dockerfile
    container_name: php
    extends:
        service: web

# ]]
# ------------------------------------------------------------------------------
# -> Python [[
# ------------------------------------------------------------------------------

  python:
    build:
      context: ./image/python
    container_name: python
    extends:
        service: web
    command: uwsgi --emperor /etc/uwsgi/vassals --vassals-include /etc/uwsgi/default.ini

# ]]
# ------------------------------------------------------------------------------
# -> Nginx [[
# ------------------------------------------------------------------------------

  nginx:
    build:
      context: ./image/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443

# ]]
# ------------------------------------------------------------------------------
# -> Mysql [[
# ------------------------------------------------------------------------------

  mysql:
    build: ./image/mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: devbox

# ]]
# ------------------------------------------------------------------------------
# -> Postgres [[
# ------------------------------------------------------------------------------

  postgres:
    image: postgres:9.6.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devbox

# ]]
# ------------------------------------------------------------------------------
# -> Mongo [[
# ------------------------------------------------------------------------------

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

# ]]
# ------------------------------------------------------------------------------
# -> Redis [[
# ------------------------------------------------------------------------------

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

# ]]
# ------------------------------------------------------------------------------
# -> Memcached [[
# ------------------------------------------------------------------------------

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - 11211:11211

# ]]
# ------------------------------------------------------------------------------
# -> Mailhog [[
# ------------------------------------------------------------------------------

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025

# ]]
# ------------------------------------------------------------------------------
# -> Adminer [[
# ------------------------------------------------------------------------------

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

# ]]
# ------------------------------------------------------------------------------
